# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woning',
            name='volledige_omschrijving',
            field=models.TextField(),
        ),
    ]
