# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funda', '0002_auto_20170717_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='woning',
            name='interessant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='woning',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
